
#ifndef _DEFAULT_CONFIG_H_
#define _DEFAULT_CONFIG_H_


#define NDEF_MAX_SIZE               (512)
#define NDEF_RECORD_MAX_SIZE        (100)

#define URI_PROTOCOL_MAX_SIZE   (20)
#define URI_MESSAGE_MAX_SIZE   (100)
#define URI_INFO_MAX_SIZE   (20)


#define TEXT_MAX_SIZE (100)
#define TEXT_LANGUAGE_CODE_MAX_SIZE (10)

#define SMS_PHONE_MAX_SIZE  (16)
#define SMS_MESSAGE_MAX_SIZE  (400)
#define SMS_INFO_MAX_SIZE  (400)

#define GEO_LATITUDE_MAX_SIZE  (20)
#define GEO_LONGITUDE_MAX_SIZE  (20)
#define GEO_INFO_MAX_SIZE  (100)

#define EMAIL_ADDRESS_MAX_SIZE  (64)
#define EMAIL_SUBJECT_MAX_SIZE  (100)
#define EMAIL_MESSAGE_MAX_SIZE  (2000)
#define EMAIL_INFO_MAX_SIZE  (400)

#endif